# config information

# server config information
server:
  mode: release # debug,release
  host: 0.0.0.0
  port: 8800
  token_expire_second: 360000
  enable_https: false  # https
  cert_file: conf/https/ibax.app.crt  # https
  key_file: conf/https/ibax.app.key # https
  jwt_public_key_path: conf/jwt/tm.rsa.pub
  jwt_private_key_path: conf/jwt/tm.rsa
  system_static_file_path: system_statics
  docs_api: http://127.0.0.1:8800 #docs api request address(explorer)

url:
  base_url: http://192.168.1.193:8802

log:
  level: error

database:
  enable: true #
  max_idle: 10 # max idle connections
  max_open: 100  #max open connections
  type: postgres # postgres
  name: scan #must be connect params sync
  ver: 20200902 #
  connect: host=127.0.0.1 port=5432 user=postgres dbname=scan sslmode=disable password=ibax20200916

# redis config information
redis:
  enable: true  #
  address: 127.0.0.1 # address
  port: 6379       # address
  password: # password
  db: 0 #db

centrifugo:
  enable: true  #
  secret: "4597e75c-4376-42a6-8c1f-7e3fc7eb2114"  #
  url: "http://127.0.0.1:8000" # address
  socket: "wss://127.0.0.1:8000/connection/websocket" # address
  key: "5872a29c-25d3-45d8-b6f2-0b36c44407cd" #

crontab:
  honor_node: "0 0/10 * * * ?"          #dashboard node map
  chart_data: "0 0/60 * * * ?"          #chart_data
  realtime: "0/4 * * * * ?"             #realtime data
  load_contracts: "0 0/20 * * * ?"      #load contracts
  history_data: "0 0/10 * * * ?"        #history data

crypto_settings:
  cryptoer: "ECC_Secp256k1"
  hasher: "KECCAK256"

defi:
  enable: true
  ecosystem: 31
